imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@SnowcapSiteBundle/Resources/config/config.yml" }
    - { resource: "@SnowcapAdminBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection:
        enabled: false
    validation:      { enable_annotations: true }
    templating:
      engines: ['twig']
      assets_version: 1.2
    session:
        default_locale: %locale%
        auto_start:     false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

parameters:
    locales: [en]

services:
  twig.extension.debug:
    class: Twig_Extensions_Extension_Debug
    tags: [ { name: 'twig.extension' } ]
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags: [ { name: 'twig.extension' } ]
  twitter:
    class: TwitterOAuth\Api
    arguments: [%twitter_consumer_key%, %twitter_consumer_secret%, %twitter_oauth_token%, %twitter_oauth_secret%]

liip_imagine:
    filter_sets:
        post_thumb:
            quality: 100
            filters:
                relative_resize: { widen: 290 }
        preview:
            quality: 100
            filters:
                thumbnail: { size: [390, 255], mode: outbound }
        thumb:
            quality: 90
            filters:
                thumbnail: { size: [290, 190], mode: outbound }
        small:
            quality: 80
            filters:
                thumbnail: { size: [100, 76], mode: outbound }

ornicar_akismet:
    api_key:        %akismet_api_key%
    url:            %akismet_url%

snowcap_admin:
    bundle: SnowcapSiteAdminBundle
    sections:
        posts:
            label: section_posts
            admin_class: Snowcap\SiteAdminBundle\Admin\PostAdmin
            entity_class: Snowcap\SiteBundle\Entity\Post
        post_categories:
            label: section_post_categories
            admin_class: Snowcap\SiteAdminBundle\Admin\PostCategoryAdmin
            entity_class: Snowcap\SiteBundle\Entity\PostCategory
        agencies:
            label: section_agencies
            admin_class: Snowcap\SiteAdminBundle\Admin\AgencyAdmin
            entity_class: Snowcap\SiteBundle\Entity\Agency
        technologies:
            label: section_technologies
            admin_class: Snowcap\SiteAdminBundle\Admin\TechnologyAdmin
            entity_class: Snowcap\SiteBundle\Entity\Technology
        images:
            label: section_images
            admin_class: Snowcap\SiteAdminBundle\Admin\ImageAdmin
            entity_class: Snowcap\SiteBundle\Entity\Image
        projects:
            label: section_projects
            admin_class: Snowcap\SiteAdminBundle\Admin\ProjectAdmin
            entity_class: Snowcap\SiteBundle\Entity\Project
