imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    snowcap_site_bundle:
        resource: @SnowcapSiteBundle/Resources/config/config.yml
    snowcap_admin_bundle:
        resource: @SnowcapAdminBundle/Resources/config/config.yml

framework:
    #esi:             ~
    translator:      { fallback: en_US }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

services:
  twig.extension.debug:
    class: Twig_Extensions_Extension_Debug
    tags: [ { name: 'twig.extension' } ]
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags: [ { name: 'twig.extension' } ]

snowcap_admin:
  content:
      post:
          label: Post
          model_class: Snowcap\SiteBundle\Entity\Post
          admin_class: Snowcap\SiteBundle\Admin\Post
      postCategory:
          label: Post Category
          model_class: Snowcap\SiteBundle\Entity\PostCategory
          admin_class: Snowcap\SiteBundle\Admin\PostCategory
      project:
          label: Case
          model_class: Snowcap\SiteBundle\Entity\Project
          admin_class: Snowcap\SiteBundle\Admin\Project
      agency:
          label: Agency
          model_class: Snowcap\SiteBundle\Entity\Agency
          admin_class: Snowcap\SiteBundle\Admin\Agency
      technology:
          label: Technology
          model_class: Snowcap\SiteBundle\Entity\Technology
          admin_class: Snowcap\SiteBundle\Admin\Technology
      image:
          label: Image
          model_class: Snowcap\SiteBundle\Entity\Image
          admin_class: Snowcap\SiteBundle\Admin\Image

avalanche_imagine:
    filters:
        thumb:
          type: thumbnail
          options: { size: [300, 230], mode: outbound }
        small:
          type: thumbnail
          options: { size: [100, 76], mode: outbound }