SnowcapAdminBundle:
    resource: "@SnowcapAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

SnowcapSiteBundleFront:
    resource: "@SnowcapSiteBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type: imagine