SnowcapSiteBundleAdmin:
    resource: "@SnowcapSiteBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin

SnowcapSiteBundleFront:
    resource: "@SnowcapSiteBundle/Controller/Front"
    type:     annotation
    prefix:   /

