SnowcapAdminBundle:
    resource: "@SnowcapAdminBundle/Controller/"
    type:     annotation
    prefix:   /newadmin

SnowcapSiteBundleAdmin:
    resource: "@SnowcapSiteBundle/Controller/Admin"
    type:     annotation
    prefix:   <?php echo getenv('admin_path')?'/'.getenv('admin_path'):'/admin'."\n"; ?>

SnowcapSiteBundleFront:
    resource: "@SnowcapSiteBundle/Controller/Front"
    type:     annotation
    prefix:   /