services:
    snowcap_core.twig:
        class: Snowcap\SiteBundle\Twig\Extension\CoreExtension
        tags:
            - { name: twig.extension }
    sitebundle.listener:
        class: Snowcap\SiteBundle\Event\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }
